/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary": "#ffffff",
        "surface": "#fcf9f3",
        "tertiary": "#090c00",
        "error": "#ba1a1a",
        "on-tertiary-fixed-variant": "#434b18",
        "tertiary-fixed-dim": "#c3cc8c",
        "primary": "#210000",
        "surface-container": "#f0eee8",
        "inverse-surface": "#31312d",
        "surface-bright": "#fcf9f3",
        "on-surface": "#1c1c18",
        "secondary-fixed-dim": "#e9c176",
        "on-tertiary-container": "#858e54",
        "outline-variant": "#dcc0bd",
        "on-primary-container": "#d26a5f",
        "surface-tint": "#9d4139",
        "inverse-primary": "#ffb4aa",
        "surface-container-highest": "#e5e2dc",
        "tertiary-fixed": "#dfe8a6",
        "surface-variant": "#e5e2dc",
        "background": "#fcf9f3",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#7e2b23",
        "on-surface-variant": "#554240",
        "primary-fixed": "#ffdad5",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "#191e00",
        "on-secondary-container": "#785a1a",
        "secondary": "#775a19",
        "surface-container-low": "#f6f3ed",
        "on-secondary-fixed-variant": "#5d4201",
        "surface-dim": "#dcdad4",
        "on-background": "#1c1c18",
        "surface-container-high": "#ebe8e2",
        "primary-container": "#4a0404",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#f3f0ea",
        "on-error-container": "#93000a",
        "secondary-container": "#fed488",
        "error-container": "#ffdad6",
        "tertiary-container": "#1e2400",
        "outline": "#89726f",
        "primary-fixed-dim": "#ffb4aa",
        "on-primary-fixed": "#410001",
        "on-secondary-fixed": "#261900",
        "on-error": "#ffffff",
        "secondary-fixed": "#ffdea5"
      },
      fontFamily: {
        "headline": ["Newsreader", "serif"],
        "body": ["Work Sans", "sans-serif"],
        "label": ["Work Sans", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem", 
        "lg": "0.25rem", 
        "xl": "0.5rem", 
        "full": "0.75rem"
      },
    },
  },
  plugins: [],
}
